export const ViewCompanyTypes = {
	TOGGLE_DIALOG: 'TOGGLE_DIALOG',
	FETCH_VIEW_COMPANY_TABLE_REQUEST: 'FETCH_VIEW_COMPANY_TABLE_REQUEST',
	FETCH_VIEW_COMPANY_TABLE_SUCCESS: 'FETCH_VIEW_COMPANY_TABLE_SUCCESS',
	FETCH_VIEW_COMPANY_TABLE_FAILURE: 'FETCH_VIEW_COMPANY_TABLE_FAILURE',
	FETCH_VIEW_COMPANY_REQUEST: 'FETCH_VIEW_COMPANY_REQUEST',
	FETCH_VIEW_COMPANY_SUCCESS: 'FETCH_VIEW_COMPANY_SUCCESS',
	FETCH_VIEW_COMPANY_FAILURE: 'FETCH_VIEW_COMPANY_FAILURE',
};
