export const ViewStudentsTypes = {
	TOGGLE_DIALOG: 'TOGGLE_DIALOG',
	FETCH_VIEW_STUDENT_TABLE_REQUEST: 'FETCH_VIEW_STUDENT_TABLE_REQUEST',
	FETCH_VIEW_STUDENT_TABLE_SUCCESS: 'FETCH_VIEW_STUDENT_TABLE_SUCCESS',
	FETCH_VIEW_STUDENT_TABLE_FAILURE: 'FETCH_VIEW_STUDENT_TABLE_FAILURE',
};
