export const ViewUpcomingTypes = {
	TOGGLE_DIALOG: 'TOGGLE_DIALOG',
	FETCH_VIEW_UPCOMING_TABLE_REQUEST: 'FETCH_VIEW_UPCOMING_TABLE_REQUEST',
	FETCH_VIEW_UPCOMING_TABLE_SUCCESS: 'FETCH_VIEW_UPCOMING_TABLE_SUCCESS',
	FETCH_VIEW_UPCOMING_TABLE_FAILURE: 'FETCH_VIEW_UPCOMING_TABLE_FAILURE',
};
