export const ViewOngoingTypes = {
	TOGGLE_DIALOG: 'TOGGLE_DIALOG',
	FETCH_VIEW_ONGOING_TABLE_REQUEST: 'FETCH_VIEW_ONGOING_TABLE_REQUEST',
	FETCH_VIEW_ONGOING_TABLE_SUCCESS: 'FETCH_VIEW_ONGOING_TABLE_SUCCESS',
	FETCH_VIEW_ONGOING_TABLE_FAILURE: 'FETCH_VIEW_ONGOING_TABLE_FAILURE',
};
